[theme]

# Primary accent for interactive elements
primaryColor = '#005358'  

# Background color for the main content area
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#f2f2f2'

# Color used for almost all text
textColor = '#302E30'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"